### ISSUE TITLE
Warnings and FutureWarnings

### ISSUE THREAD

**Issue by groadabike** [mir-aidj/all-in-one#24]
Hi, 

Thank you for this great tool
Just wanted to let you know that Natten is raising a lot of Warnings and FutureWarnings when running the model using CLI.

To make this simple, I am just copying here the 4 warnings I am getting. But notice that the process is printing these Warnings many times, at leats 40 times.

```
/home/gerardoroadabike/anaconda3/envs/allinone/lib/python3.11/site-packages/natten/functional.py:1264: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/gerardoroadabike/anaconda3/envs/allinone/lib/python3.11/site-packages/natten/functional.py:1336: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

...

| 2024-10-24 16:41:04,459 | [[ natten.functional ]] [ WARNING ]: You're calling NATTEN op `natten.functional.natten1dqkrpb`, which is deprecated in favor of `natten.functional.na1d_qk`. Please consider switching, as this op will be removed soon.
| 2024-10-24 16:41:05,464 | [[ natten.functional ]] [ WARNING ]: You're calling NATTEN op `natten.functional.natten1dav`, which is deprecated in favor of `natten.functional.na1d_av`. Please consider switching, as this op will be removed soon.
```

My system
Linux. 
CPU system
**Pytorch 2.4.0** 
conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 cpuonly -c pytorch

**Natten**
pip3 install natten==0.17.1+torch240cpu -f https://shi-labs.com/natten/wheels

pip install git+https://github.com/CPJKU/madmom  # install the latest madmom directly from GitHub
pip install allin1

**Comment by deniro21** [comment]
Same errors...

**Comment by Tetsujinfr** [comment]
fyi now using natten-0.17.5+torch260cu126 , those warnings are not warnings anymore but trigger errors, such as:
`ImportError: cannot import name 'natten1dav' from 'natten.functional'`
or `cannot import name 'natten1dqkrpb' from 'natten.functional'`

So Natten has refactored a bunch of functions/modules, and all-in-one current version cannot deal with those broken dependencies.

In the meantime, ifone wants to get it to work with Natten v0.17.5, in the all-in-one repo code in the dinat.py file, just replace the below line by the next one:

~~from natten.functional import natten1dav, natten1dqkrpb, natten2dav, natten2dqkrpb~~
`from natten.functional import na1d_av, na1d_qk, na2d_av, `na2d_qk`


Quick and dirty fix, but works. hopefully usefull for some users here. => @groadabike I suggest you close this issue

**Comment by kyleawayan** [comment]
Thanks, replacing the new imports worked for me. I also had to replace the references to the old imports, as well as change the function arguments since those were changed as well:

`dinat.py`:
```diff
@@ -7,7 +7,7 @@ import math
 import torch
 from abc import ABC,  abstractmethod
 from typing import Optional, Tuple, Callable
-from natten.functional import natten1dav, natten1dqkrpb, natten2dav, natten2dqkrpb
+from natten.functional import na1d_av, na1d_qk, na2d_av, na2d_qk
 from ..config import Config
 from .utils import *
 
@@ -96,7 +96,7 @@ class _NeighborhoodAttentionNd(ABC, nn.Module):
     
     # Compute NA between "query" and "key" to get the raw attention scores, and add relative positional biases.
     # attention_scores = natten2dqkrpb(query_layer, key_layer, self.rpb, self.dilation)
-    attention_scores = self.nattendqkrpb(query_layer, key_layer, self.rpb, self.kernel_size, self.dilation)
+    attention_scores = self.nattendqkrpb(query_layer, key_layer, self.kernel_size, self.dilation, None, False, self.rpb)
     
     # Normalize the attention scores to probabilities.
     attention_probs = nn.functional.softmax(attention_scores, dim=-1)
@@ -141,8 +141,8 @@ class NeighborhoodAttention1d(_NeighborhoodAttentionNd):
       torch.zeros(num_heads, (2 * self.kernel_size - 1)),
       requires_grad=True,
     )
-    self.nattendqkrpb = natten1dqkrpb
-    self.nattendav = natten1dav
+    self.nattendqkrpb = na1d_qk
+    self.nattendav = na1d_av
 
 
 class NeighborhoodAttention2d(_NeighborhoodAttentionNd):
@@ -159,8 +159,8 @@ class NeighborhoodAttention2d(_NeighborhoodAttentionNd):
       torch.zeros(num_heads, (2 * self.kernel_size - 1), (2 * self.kernel_size - 1)),
       requires_grad=True,
     )
-    self.nattendqkrpb = natten2dqkrpb
-    self.nattendav = natten2dav
+    self.nattendqkrpb = na2d_qk
+    self.nattendav = na2d_av
 
 
 # Copied from transformers.models.nat.modeling_nat.NeighborhoodAttentionOutput
```
